spring:
  application:
    name: auth-service
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: auth-service:${random.value}  # para evitar conflictos de registro duplicado
