spring:
  application:
    name: auth-service

  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: segura123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    enabled: false
