spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: theater-service
          uri: lb://theater-service
          predicates:
            - Path=/theaters/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8080
