spring:
  application:
    name: theater-service  # distinto en cada microservicio
  datasource:
    url: jdbc:h2:mem:testdb  # O tu base PostgreSQL si vas a conectar una
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0  # para que tome uno aleatorio